### ISSUE TITLE
Clear branch 

### ISSUE THREAD

**Issue by siwonblue** [Team-Momu/momu-client#46]
림채야
브랜치 바로바로 지우는 습관 가지자 ^^

**Comment by chaaerim** [comment]
ㅋ ㅋ ㅋㅋㅋ저 아직 기능 구현 안끝나서 안지운 건디요 ... ^^ 그냥 제가 문제져 빨리 끝내겠습니다 ^^

**Comment by siwonblue** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
림채김 든든하다
